org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35
android.aapt2FromMavenOverride=/usr/lib/android-sdk/build-tools/34.0.0/aapt2
org.gradle.workers.max=2
android.enableAapt2Daemon=false
android.aapt2.threadPoolSize=1
